collections_dir: collections

collections:
  articles:
    filename: "{{ published_at | date: '%Y-%m-%d' }}-{{ slug }}"
    content: body
    output: false
  categories:
    output: false
  testables:
    output: false
  videos:
    output: false

contentful:
  exclude:
    - migrations
  article:
    map:
      name: title
    belongs_to:
      category: posts
