collections_dir: collections

collections:
  articles:
    output: true
    permalink: /:collection/:slug
  podcasts:
    output: true
    permalink: /:collection/:slug
  series:
    output: true
    permalink: /:collection/:slug
  messages:
    output: true
    permalink: /:collection/:slug

contentful:
  content_types:
    articles:
      id: article
      body: body
      filename: "{{ published_at | date: '%Y-%m-%d' }}-{{ slug }}"
      frontmatter:
        entry_mappings:
          title: title
          image: image/url
          author: author/full_name
          topic: category/title
          date: published_at
          slug: slug
          tags: tags
        other:
          layout: article
          draft: false
    podcasts:
      id: podcast
      body: this_field_doesnt_exist
      frontmatter:
        entry_mappings:
          title: title
          subtitle: subtitle
          image: image/url
          background: bg_image/url
          authors: author/full_name
          apple_podcasts_url: apple_podcasts_url
          google_play_url: google_play_url
          stitcher_url: stitcher_url
          slug: slug
        other:
          layout: podcast
          draft: false
    series:
      id: series
      body: description
      frontmatter:
        entry_mappings:
          title: title
          slug: slug
          image: image/url
          bg_image: background_image/url
          start_date: starts_at
          end_date: ends_at
          youtube_url: youtube_url
          apple_podcasts_url: apple_podcasts_url
          google_play_url: google_play_url
          year: "{{ starts_at | date: '%Y' }}"
        other:
          layout: series
          draft: false
    messages:
      id: message
      body: description
      links:
        series_slug:
          content_type: series
          linked_field: videos
          display_field: slug
      frontmatter:
        entry_mappings:
          title: title
          authors: author/full_name
          image: image/url
          source_url: source_url
          series: series/title
          program: program/url
          video_duration: video_duration
          topic: category/title
          topic_slug: category/slug
          tags: tags
          transcription: transcription
          apple_podcasts_url: apple_podcasts_url
          google_play_url: google_play_url
          date: published_at
          slug: slug
        other:
          layout: video
          draft: false
