collections_dir: collections

collections:
  articles:
    output: true
    permalink: /:collection/:slug
  podcasts:
    output: true
    permalink: /:collection/:slug
  messages:
    output: true
    permalink: /:collection/:slug
  series:
    output: true
    permalink: /:collection/:slug
  trailers:
    output: true
    permalink: /:collection/:slug

contentful:
  content_types:
    articles:
      id: article
      body: body
      filename: "{{ published_at | date: '%Y-%m-%d' }}-{{ slug }}"
      frontmatter:
        entry_mappings:
          title: title
          image: image/url
          author: author/full_name
          topic: category/title
          date: published_at
          slug: slug
          tags: tags
        other:
          layout: article
          draft: false
    podcasts:
      id: podcast
      body: this_field_doesnt_exist
      frontmatter:
        entry_mappings:
          title: title
          subtitle: subtitle
          image: image/url
          background: bg_image/url
          authors: author/full_name
          apple_podcasts_url: apple_podcasts_url
          google_play_url: google_play_url
          stitcher_url: stitcher_url
          slug: slug
        other:
          layout: podcast
          draft: false
    messages:
      id: message
      frontmatter:
        entry_mappings:
          title: title
          slug: slug
    series:
      id: series
      associations:
        videos:
          - trailers
          - messages
      frontmatter:
        entry_mappings:
          title: title
          videos: videos/id
          slug: slug
    trailers:
      id: trailer
      frontmatter:
        entry_mappings:
          title: title
          slug: slug
