collections_dir: collections

collections:
  articles:
    output: true
    permalink: /articles/:slug

contentful:
  content_types:
    articles:
      id: article
      body: body
      filename: "{{ published_at | date: '%Y-%m-%d' }}-{{ slug }}"
      frontmatter:
        entry_mappings:
          title: title
          image: image/url
          author: author/full_name
          topic: category/title
          date: published_at
          slug: slug
          tags: tags
        other:
          layout: article
          draft: false
